//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proaraz
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч рег входа.
    /// </summary>
    // *** Start programmer edit section *** (ТЧРегВхода CustomAttributes)

    // *** End programmer edit section *** (ТЧРегВхода CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч рег входа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧРегВходаE", new string[] {
            "Карты as \'Карты\'",
            "Карты.КодКарты as \'Код карты\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Гость as \'Гость\'",
            "Гость.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Карты.КодКарты",
            "Сотрудник.Фамилия",
            "Гость.Фамилия"})]
    [MasterViewDefineAttribute("ТЧРегВходаE", "Карты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодКарты")]
    [MasterViewDefineAttribute("ТЧРегВходаE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ТЧРегВходаE", "Гость", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    public class ТЧРегВхода : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Proaraz.Карты fКарты;
        
        private IIS.Proaraz.Сотрудник fСотрудник;
        
        private IIS.Proaraz.Гость fГость;
        
        private IIS.Proaraz.ФормаРегВхода fФормаРегВхода;
        
        // *** Start programmer edit section *** (ТЧРегВхода CustomMembers)

        // *** End programmer edit section *** (ТЧРегВхода CustomMembers)

        
        /// <summary>
        /// Т ч рег входа.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхода.Гость CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхода.Гость CustomAttributes)
        [PropertyStorage(new string[] {
                "Гость"})]
        [NotNull()]
        public virtual IIS.Proaraz.Гость Гость
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхода.Гость Get start)

                // *** End programmer edit section *** (ТЧРегВхода.Гость Get start)
                IIS.Proaraz.Гость result = this.fГость;
                // *** Start programmer edit section *** (ТЧРегВхода.Гость Get end)

                // *** End programmer edit section *** (ТЧРегВхода.Гость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхода.Гость Set start)

                // *** End programmer edit section *** (ТЧРегВхода.Гость Set start)
                this.fГость = value;
                // *** Start programmer edit section *** (ТЧРегВхода.Гость Set end)

                // *** End programmer edit section *** (ТЧРегВхода.Гость Set end)
            }
        }
        
        /// <summary>
        /// Т ч рег входа.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхода.Карты CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхода.Карты CustomAttributes)
        [PropertyStorage(new string[] {
                "Карты"})]
        [NotNull()]
        public virtual IIS.Proaraz.Карты Карты
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхода.Карты Get start)

                // *** End programmer edit section *** (ТЧРегВхода.Карты Get start)
                IIS.Proaraz.Карты result = this.fКарты;
                // *** Start programmer edit section *** (ТЧРегВхода.Карты Get end)

                // *** End programmer edit section *** (ТЧРегВхода.Карты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхода.Карты Set start)

                // *** End programmer edit section *** (ТЧРегВхода.Карты Set start)
                this.fКарты = value;
                // *** Start programmer edit section *** (ТЧРегВхода.Карты Set end)

                // *** End programmer edit section *** (ТЧРегВхода.Карты Set end)
            }
        }
        
        /// <summary>
        /// Т ч рег входа.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхода.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхода.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Proaraz.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхода.Сотрудник Get start)

                // *** End programmer edit section *** (ТЧРегВхода.Сотрудник Get start)
                IIS.Proaraz.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (ТЧРегВхода.Сотрудник Get end)

                // *** End programmer edit section *** (ТЧРегВхода.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхода.Сотрудник Set start)

                // *** End programmer edit section *** (ТЧРегВхода.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (ТЧРегВхода.Сотрудник Set end)

                // *** End programmer edit section *** (ТЧРегВхода.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proaraz.ФормаРегВхода.
        /// </summary>
        // *** Start programmer edit section *** (ТЧРегВхода.ФормаРегВхода CustomAttributes)

        // *** End programmer edit section *** (ТЧРегВхода.ФормаРегВхода CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ФормаРегВхода"})]
        public virtual IIS.Proaraz.ФормаРегВхода ФормаРегВхода
        {
            get
            {
                // *** Start programmer edit section *** (ТЧРегВхода.ФормаРегВхода Get start)

                // *** End programmer edit section *** (ТЧРегВхода.ФормаРегВхода Get start)
                IIS.Proaraz.ФормаРегВхода result = this.fФормаРегВхода;
                // *** Start programmer edit section *** (ТЧРегВхода.ФормаРегВхода Get end)

                // *** End programmer edit section *** (ТЧРегВхода.ФормаРегВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧРегВхода.ФормаРегВхода Set start)

                // *** End programmer edit section *** (ТЧРегВхода.ФормаРегВхода Set start)
                this.fФормаРегВхода = value;
                // *** Start programmer edit section *** (ТЧРегВхода.ФормаРегВхода Set end)

                // *** End programmer edit section *** (ТЧРегВхода.ФормаРегВхода Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧРегВходаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧРегВходаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧРегВходаE", typeof(IIS.Proaraz.ТЧРегВхода));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧРегВхода.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧРегВхода CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧРегВхода CustomAttributes)
    public class DetailArrayOfТЧРегВхода : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Proaraz.DetailArrayOfТЧРегВхода members)

        // *** End programmer edit section *** (IIS.Proaraz.DetailArrayOfТЧРегВхода members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧРегВхода by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧРегВхода.
        /// </summary>
        public DetailArrayOfТЧРегВхода(IIS.Proaraz.ФормаРегВхода fФормаРегВхода) : 
                base(typeof(ТЧРегВхода), ((ICSSoft.STORMNET.DataObject)(fФормаРегВхода)))
        {
        }
        
        public IIS.Proaraz.ТЧРегВхода this[int index]
        {
            get
            {
                return ((IIS.Proaraz.ТЧРегВхода)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Proaraz.ТЧРегВхода dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
