//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proaraz
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Форма рег карт.
    /// </summary>
    // *** Start programmer edit section *** (ФормаРегКарт CustomAttributes)

    // *** End programmer edit section *** (ФормаРегКарт CustomAttributes)
    [AutoAltered()]
    [Caption("Форма рег карт")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормаРегКартE", new string[] {
            "Дата as \'Дата\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Комната as \'Комната\'",
            "Комната.Номер as \'Номер\'",
            "Гость as \'Гость\'",
            "Гость.Фамилия as \'Фамилия\'",
            "Карты as \'Карты\'",
            "Карты.КодКарты as \'Код карты\'"}, Hidden=new string[] {
            "Сотрудник.Фамилия",
            "Комната.Номер",
            "Гость.Фамилия",
            "Карты.КодКарты"})]
    [MasterViewDefineAttribute("ФормаРегКартE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ФормаРегКартE", "Комната", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [MasterViewDefineAttribute("ФормаРегКартE", "Гость", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ФормаРегКартE", "Карты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодКарты")]
    [View("ФормаРегКартL", new string[] {
            "Дата as \'Дата\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Комната.Номер as \'Номер\'",
            "Гость.Фамилия as \'Фамилия\'",
            "Карты.КодКарты as \'Код карты\'"})]
    public class ФормаРегКарт : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.Proaraz.Сотрудник fСотрудник;
        
        private IIS.Proaraz.Комната fКомната;
        
        private IIS.Proaraz.Гость fГость;
        
        private IIS.Proaraz.Карты fКарты;
        
        // *** Start programmer edit section *** (ФормаРегКарт CustomMembers)

        // *** End programmer edit section *** (ФормаРегКарт CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ФормаРегКарт.Дата CustomAttributes)

        // *** End programmer edit section *** (ФормаРегКарт.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Дата Get start)

                // *** End programmer edit section *** (ФормаРегКарт.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ФормаРегКарт.Дата Get end)

                // *** End programmer edit section *** (ФормаРегКарт.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Дата Set start)

                // *** End programmer edit section *** (ФормаРегКарт.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ФормаРегКарт.Дата Set end)

                // *** End programmer edit section *** (ФормаРегКарт.Дата Set end)
            }
        }
        
        /// <summary>
        /// Форма рег карт.
        /// </summary>
        // *** Start programmer edit section *** (ФормаРегКарт.Гость CustomAttributes)

        // *** End programmer edit section *** (ФормаРегКарт.Гость CustomAttributes)
        [PropertyStorage(new string[] {
                "Гость"})]
        [NotNull()]
        public virtual IIS.Proaraz.Гость Гость
        {
            get
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Гость Get start)

                // *** End programmer edit section *** (ФормаРегКарт.Гость Get start)
                IIS.Proaraz.Гость result = this.fГость;
                // *** Start programmer edit section *** (ФормаРегКарт.Гость Get end)

                // *** End programmer edit section *** (ФормаРегКарт.Гость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Гость Set start)

                // *** End programmer edit section *** (ФормаРегКарт.Гость Set start)
                this.fГость = value;
                // *** Start programmer edit section *** (ФормаРегКарт.Гость Set end)

                // *** End programmer edit section *** (ФормаРегКарт.Гость Set end)
            }
        }
        
        /// <summary>
        /// Форма рег карт.
        /// </summary>
        // *** Start programmer edit section *** (ФормаРегКарт.Карты CustomAttributes)

        // *** End programmer edit section *** (ФормаРегКарт.Карты CustomAttributes)
        [PropertyStorage(new string[] {
                "Карты"})]
        [NotNull()]
        public virtual IIS.Proaraz.Карты Карты
        {
            get
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Карты Get start)

                // *** End programmer edit section *** (ФормаРегКарт.Карты Get start)
                IIS.Proaraz.Карты result = this.fКарты;
                // *** Start programmer edit section *** (ФормаРегКарт.Карты Get end)

                // *** End programmer edit section *** (ФормаРегКарт.Карты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Карты Set start)

                // *** End programmer edit section *** (ФормаРегКарт.Карты Set start)
                this.fКарты = value;
                // *** Start programmer edit section *** (ФормаРегКарт.Карты Set end)

                // *** End programmer edit section *** (ФормаРегКарт.Карты Set end)
            }
        }
        
        /// <summary>
        /// Форма рег карт.
        /// </summary>
        // *** Start programmer edit section *** (ФормаРегКарт.Комната CustomAttributes)

        // *** End programmer edit section *** (ФормаРегКарт.Комната CustomAttributes)
        [PropertyStorage(new string[] {
                "Комната"})]
        [NotNull()]
        public virtual IIS.Proaraz.Комната Комната
        {
            get
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Комната Get start)

                // *** End programmer edit section *** (ФормаРегКарт.Комната Get start)
                IIS.Proaraz.Комната result = this.fКомната;
                // *** Start programmer edit section *** (ФормаРегКарт.Комната Get end)

                // *** End programmer edit section *** (ФормаРегКарт.Комната Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Комната Set start)

                // *** End programmer edit section *** (ФормаРегКарт.Комната Set start)
                this.fКомната = value;
                // *** Start programmer edit section *** (ФормаРегКарт.Комната Set end)

                // *** End programmer edit section *** (ФормаРегКарт.Комната Set end)
            }
        }
        
        /// <summary>
        /// Форма рег карт.
        /// </summary>
        // *** Start programmer edit section *** (ФормаРегКарт.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (ФормаРегКарт.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Proaraz.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Сотрудник Get start)

                // *** End programmer edit section *** (ФормаРегКарт.Сотрудник Get start)
                IIS.Proaraz.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (ФормаРегКарт.Сотрудник Get end)

                // *** End programmer edit section *** (ФормаРегКарт.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Сотрудник Set start)

                // *** End programmer edit section *** (ФормаРегКарт.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (ФормаРегКарт.Сотрудник Set end)

                // *** End programmer edit section *** (ФормаРегКарт.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормаРегКартE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаРегКартE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаРегКартE", typeof(IIS.Proaraz.ФормаРегКарт));
                }
            }
            
            /// <summary>
            /// "ФормаРегКартL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаРегКартL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаРегКартL", typeof(IIS.Proaraz.ФормаРегКарт));
                }
            }
        }
    }
}
